### ISSUE TITLE
error by build on Ubuntu 21.10

### ISSUE THREAD

**Issue by gorenstein** [madMAx43v3r/mmx-node#5]
error by run ./make_devel.sh
```
...
[ 60%] Built target relic_s
[ 60%] Built target bls
In file included from /home/serge/mmx-node/vnx-addons/lib/url-cpp/src/punycode.cpp:5:
/home/serge/mmx-node/vnx-addons/lib/url-cpp/include/punycode.h:56:54: error: ‘numeric_limits’ is not a member of ‘std’
   56 |         const punycode_uint MAX_PUNYCODE_UINT = std::numeric_limits<punycode_uint>::max();
      |                                                      ^~~~~~~~~~~~~~
compilation terminated due to -fmax-errors=1.
make[2]: *** [vnx-addons/CMakeFiles/url_cpp.dir/build.make:95: vnx-addons/CMakeFiles/url_cpp.dir/lib/url-cpp/src/punycode.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/serge/mmx-node/vnx-addons/lib/url-cpp/src/url.cpp:11:
/home/serge/mmx-node/vnx-addons/lib/url-cpp/include/punycode.h:56:54: error: ‘numeric_limits’ is not a member of ‘std’
   56 |         const punycode_uint MAX_PUNYCODE_UINT = std::numeric_limits<punycode_uint>::max();
      |                                                      ^~~~~~~~~~~~~~
compilation terminated due to -fmax-errors=1.
make[2]: *** [vnx-addons/CMakeFiles/url_cpp.dir/build.make:108: vnx-addons/CMakeFiles/url_cpp.dir/lib/url-cpp/src/url.cpp.o] Error 1
In file included from /home/serge/mmx-node/vnx-addons/lib/url-cpp/src/psl.cpp:7:
/home/serge/mmx-node/vnx-addons/lib/url-cpp/include/punycode.h:56:54: error: ‘numeric_limits’ is not a member of ‘std’
   56 |         const punycode_uint MAX_PUNYCODE_UINT = std::numeric_limits<punycode_uint>::max();
      |                                                      ^~~~~~~~~~~~~~
compilation terminated due to -fmax-errors=1.
make[2]: *** [vnx-addons/CMakeFiles/url_cpp.dir/build.make:82: vnx-addons/CMakeFiles/url_cpp.dir/lib/url-cpp/src/psl.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:889: vnx-addons/CMakeFiles/url_cpp.dir/all] Error 2
make: *** [Makefile:149: all] Error 2

```

**Comment by madMAx43v3r** [comment]
fixed in latest, update via `git pull && git submodule update --init --recursive && ./make_devel.sh`

**Comment by gorenstein** [comment]
now it works for me, thanks
