### ISSUE TITLE
/lib/lexy needs update to compile with clang 19.1.1

### ISSUE THREAD

**Issue by voidxno** [madMAx43v3r/mmx-node#269]
**Environment:**
- OS: Ubuntu 24.10
- Compiler: clang 19.1.1

**Problem:**
- Compiling mmx-node with **clang results in following error** (no problem with gcc):
```
In file included from /home/user/mmx-node/lib/lexy/include/lexy/action/trace.hpp:9:
/home/user/mmx-node/lib/lexy/include/lexy/input_location.hpp:183:37: error: no member named '_colum_nr' in 'input_location<Input, Counting>'; did you mean '_column_nr'?
  183 |         return lhs._column_nr < rhs._colum_nr;
      |                                     ^~~~~~~~~
      |                                     _column_nr
/home/user/mmx-node/lib/lexy/include/lexy/input_location.hpp:206:24: note: '_column_nr' declared here
  206 |     unsigned _line_nr, _column_nr;
```

**Solution:**
- Commit [lexy @ e8eb4d6](https://github.com/foonathan/lexy/commit/e8eb4d67c4eb33e1476218c0374f68e198723526) from **03may2024**, **fixes typo**
- mmx-node currently at [lexy @ 0017631](https://github.com/foonathan/lexy/commit/0017631830f6572d1f66ef1856b8e796b27bcbe2) from 02may2024
- Update to a point with typo fix

**Observation:**
- No problem with gcc 14.2.0. Maybe some C++ feature support differentiate.

**Comment by madMAx43v3r** [comment]
Should be fixed in `mainnet-rc` now.

**Comment by voidxno** [comment]
Solved, thx.
